---
title: "Creating a GitHub Account"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Kayleen Carlson
Predictive Modeling 
Week 8 Creating a GitHub Account

__Week 1:__  
    
1. I learned what an R Markdown file was and how to use it. I will always use them going forward.   
2. I learned about model variance and bias and the tradeoffs associated with higher and lower values of each and how to choose an optimal model.    

__Week 2:__  

1. I learned how to normalize data. Normalization is having absolute quantaties rather than relative.  
2. I looked into the differences between exploratory and explanatory analysis and know that both are equally necessary.  

__Week 3:__  

1. I learned how to use boxplots to see distributions by class to determine whether or not to include the variables in the next step of building the model.  
2. I learned about different ways to measure the quality of model predictions. I liked the method of residual error.   

__Week 4:__

1. I learned about confusion matricies and how to measure precision and recall based off of the true positives, true negatives, false positives and false negatives.  
2. I learned about the ROC curve and how to use it with binary classifiers. Looking at the area under the curve we can compare classifiers.  

__Week 5:__ 

1. I learned that Generalized linear models are a form of regression model where the data is not normally distributed. 
2. I learned that a gamma regression is appropriate when the distribution of the target variable is non-negative and skewed to the right on a histogram.  

__Week 6:__  

1. I learned how to prune a decision tree model which is removing one or more splits in order to produce the best model. 
2. I learned that gradient boosting machines are prone to overfitting and it takes careful work to make sure they are not overfit.  

__Week 7:__

1. I learned that it takes a really long time for R to determine the optimal number of k means clusters with really large datasets.  
2. I learned that google news uses unsupervised learning algoithms to search across all news sources to gather information.   

__Week 8:__  

1. I learned that all of this data analyis is useless unless you can communicate your results.  
2. I leaned what Github is and how to use it to collaborate with others.  